### PR TITLE
WIP: Show map with location and list of attendees on event panel

### PR DESCRIPTION
**Pull request by adeeldb**

### CODE REVIEW

**Comment by adjscent** [comment]
@adeeldb make sure travis passes

**Comment by agendazhang** [comment]
Great commit

**Comment by adjscent** [comment]
image

@adeeldb Please fix the google maps. Please fix the {} tags. Please use the event poll display instead.

**Comment by adjscent** [comment]
We are closing this pull request as it does not pass our CI tests.

**Pull request closed without merging**
