### PR TITLE
Resolve Issue #190 and Issue #198 

### PR DESCRIPTION
**Pull request by yao-feng**

### CODE REVIEW

**Comment by theJrLinguist** [comment]
Did you make sure to throw an exception if the user does not specify any attributes to the findUser command

**Comment by yao-feng** [comment]
@theJrLinguist Yeah, just checked.

**Comment by yao-feng** [comment]
@agendazhang Doesn't it detect interests before?

**Comment by agendazhang** [comment]
It doesnt if interest is the only parameter passed in. But i have fixed it in my pr already

**Pull request merged**
